### ISSUE TITLE
MOBI file in repo doesn't render math

### ISSUE THREAD

**Issue by garymm** [CompCogNeuro/book#6]
Viewing ccnbook_ed4.mobi on various Kindle apps and on Calibre, all of the math is totally missing.
The ePub version is fine.
Converting the ePub to MOBI with Calibre also results in the math being missing.

**Comment by rcoreilly** [comment]
mobi has been deprecated by Amazon -- new format is kpf -- apparently you can also directly read .epub on kindle too via email.  I have done the kpf conversion for my other textbook but not yet on this one.

**Comment by garymm** [comment]
I guess closing since MOBI is deprecated.
